Feature/sign in screen
LookUpGroup27/LookUp pull request #23
Opened 2024-10-12 11:19 UTC by Ismaillat

Add SignIn feature and UI tests.
Add the gms plugin in the app level gradle.

2024-10-12 12:43 UTC, AdrienBousquieEPFL requested changes
You need to update the branch by merging it with the current state of the main branch and resolve the potential conflicts. By the way, I annotated some things that we can change and things that we can discuss to prepare for modularity with the dark mode. Otherwise, the tests and the code is fine 👍

2024-10-12 12:43 UTC, AdrienBousquieEPFL commented on app/src/main/java/com/github/lookupgroup27/lookup/ui/authentication/SignIn.kt
> +            //navigationActions.navigateTo(TopLevelDestinations.MAP) To be implemented
Mark it as a TODO

2024-10-12 12:43 UTC, AdrienBousquieEPFL commented on app/src/main/res/drawable/app_logo.png
We should change the logo with an opacity of 0 behind to make the logo displayable for dark and light theme. We also need one with a white planet and "UP" to adapt for the dark theme.
@othbcq Can you do this ?

2024-10-12 13:06 UTC, othbcq commented on app/src/main/res/drawable/app_logo.png
Yes, I'll do it

2024-10-12 15:44 UTC, othbcq commented on app/src/main/res/drawable/app_logo.png
Here
![Design sans titre-22](https://github.com/user-attachments/assets/1b8009dc-041e-4a95-ba84-200fcc069a0d)

2024-10-13 17:41 UTC, AdrienBousquieEPFL commented
> ## [![Quality Gate Failed](https://camo.githubusercontent.com/ce402bcc4cf818eda660128f0b27a891eb8c9f4e0d783303ea667cb0d4b07f95/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f71672d6661696c65642d323070782e706e67)](https://sonarcloud.io/dashboard?id=LookUpGroup27_LookUp&pullRequest=23) **Quality Gate failed**
> Failed conditions ![](https://camo.githubusercontent.com/bd1d5234b37410841ad8cd9d85c84eeecaec92ae18a95c926ae3a59a17c29a65/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6661696c65642d313670782e706e67) [68.5% Coverage on New Code](https://sonarcloud.io/component_measures?id=LookUpGroup27_LookUp&pullRequest=23&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=LookUpGroup27_LookUp&pullRequest=23)

We will actually skip this for now and add an issue to actually fix this code coverage problem on the SignIn.kt file later.

2024-10-14 10:04 UTC, merged