feat: Implement CollectionScreen with Firebase image loading and UI tests
LookUpGroup27/LookUp pull request #92
Opened 2024-11-04 01:26 UTC by othbcq

### Summary

This PR introduces the implementation of the `CollectionScreen` composable, allowing users to view their astronomy image collection directly within the app. The screen is fully integrated with Firebase Storage to dynamically load and display images. Additionally, the UI has been optimized for a two-column grid layout, with a scrollable design to accommodate extensive collections.

### Changes

- **Implemented CollectionScreen Composable**
  - Built a complete `CollectionScreen` composable to display images from Firebase Storage.
  - Configured a two-column grid layout for presenting images in chronological order.
  - Added a fallback message for when no images are available in the collection.
  
- **Firebase Integration**
  - Implemented error handling and user feedback in case of load failures.

- **UI Test Tags & Testing Enhancements**
  - Added unique `testTags` to key UI elements for reliable testing.
  - Developed unit tests to verify the display of key elements (background image, title text, image grid) and interactions (back button functionality).
  - Increased test coverage for `CollectionScreen` to ensure functionality and reliability.

2024-11-07 16:54 UTC, Ismaillat requested changes
Overall code looks good to me, still need to ensure that imageUrl is not null before using it.

2024-11-07 16:54 UTC, Ismaillat commented on app/src/main/java/com/github/lookupgroup27/lookup/ui/profile/Collection.kt
> +                    item.downloadUrl.addOnSuccessListener { uri -> imageUrls.add(uri.toString()) }
Ensure that any retrieved image URLs are valid and non-null before adding them to imageUrls to avoid potential null pointer exceptions in the UI.

2024-11-07 23:26 UTC, AdrienBousquieEPFL reviewed
Everything looks fine for me, I will just put the library into the catalog.

2024-11-07 23:26 UTC, AdrienBousquieEPFL commented on app/build.gradle.kts
> +    implementation("io.coil-kt:coil-compose:2.1.0")
The library should be added to the library catalog `libs.versions.toml`

2024-11-07 23:29 UTC, AdrienBousquieEPFL approved these changes
Everything looks fine to me !

2024-11-08 01:11 UTC, Ismaillat approved these changes
Looks good to me.

2024-11-08 07:19 UTC, merged

2024-11-11 09:36 UTC, othbcq commented
I created a new issue to refactor the code since this code doesn't respect the MVVM architecture. I will create a viewModel and a Repository for the collection.